### ISSUE TITLE
Cannot figure out correct URL to see my product page

### ISSUE THREAD

**Issue by MissMadore** [MissMadore/ecommerce-pattern-library#2]
Hi @thomasjbradley

I followed the lesson under Week 10 "Preparing Product Data" and couldn't figure out what url I was meant to plug in in order to test viewing my page. Could you please clarify this for me? I just want to make sure that its working before I move on, and then I will hustle on catching up with the rest of my site. 

Many thanks, hope you're doing well. RIP JS workshop :shipit:

**Comment by thomasjbradley** [comment]
It’s not likely working right now because of an indentation problem inside `_config.yml`:
https://github.com/MissMadore/ecommerce-pattern-library/blob/master/_config.yml#L20-L27

These should be outdented one level further, `collections` & `defaults` touching the sides.

And `output` should be set to `true`: `output: true`

**Comment by thomasjbradley** [comment]
After that, the test URL will be: 

```
http://localhost:4000/produts/artwork-1/
```

**Comment by MissMadore** [comment]
It's working! Thank you so much 👍
